#!/bin/sh

ROOT=$(dirname $0)

show_spec () {
	local T="$1"
	local N="$2"

	echo "# $T $N"
	echo
	cat "$ROOT/$T/$N.spec" 2> /dev/zero
	echo
}

show_spec conf	link-base
show_spec conf	link-ethernet
show_spec conf	link-bonding
show_spec conf	link-bridge

show_spec conf  service-ntp
